services:

  shutter-api:
    image: ghcr.io/astral-sh/uv:python3.13-alpine
    volumes:
      - ./simple.py:/simple.py
    networks:
      - caddy
    command: uv run --script /simple.py
    restart: unless-stopped
    labels:
      caddy: localhost:80
      caddy.reverse_proxy: "{{upstreams 8008}}"

  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    ports:
      - 80:80
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy_data/config:/config
    restart: unless-stopped
    entrypoint: /usr/bin/caddy
    command: docker-proxy run

networks:
  caddy:
    external: true
